name: core_package
description: >
  A reusable Flutter foundation package providing networking, error handling,
  logging, validation, a configurable theming contract, and base architecture
  classes for Clean Architecture apps.
version: 0.1.0
homepage: https://github.com/Gurpreets11/core-package
repository: https://github.com/Gurpreets11/core-package
issue_tracker: https://github.com/Gurpreets11/core-package/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  meta: ^1.11.0
  connectivity_plus: ^6.0.5
  flutter_secure_storage: ^9.2.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3
  http_mock_adapter: ^0.6.1

flutter:
